In [1]:
import tensorflow as tf
from unsupervised_models.variational_autoencoder import VariationalAutoencoder, read_images, get_batch, min_max_scale
%load_ext autoreload

In [27]:
IMAGE_PATH = "/Users/Jimmy/Pictures"


data = read_images(IMAGE_PATH)
print("Read data")

3it [00:00, 18.28it/s]

[[[181 183 182]
  [178 180 179]
  [175 177 176]
  ..., 
  [133 135 132]
  [126 128 125]
  [123 125 122]]

 [[175 177 176]
  [176 178 177]
  [171 173 172]
  ..., 
  [136 138 135]
  [130 132 129]
  [118 120 117]]

 [[161 163 162]
  [167 169 168]
  [160 162 161]
  ..., 
  [122 124 121]
  [114 116 113]
  [ 93  95  92]]

 ..., 
 [[ 25  11  26]
  [ 27  13  28]
  [ 29  15  30]
  ..., 
  [ 22   9  19]
  [ 23  10  20]
  [ 23  10  20]]

 [[ 26  12  27]
  [ 28  14  29]
  [ 30  16  31]
  ..., 
  [ 22   9  19]
  [ 23  10  20]
  [ 23  10  20]]

 [[ 28  11  27]
  [ 30  13  29]
  [ 31  14  30]
  ..., 
  [ 22   9  19]
  [ 23  10  20]
  [ 23  10  20]]]
[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 25

5it [00:00, 16.00it/s]

[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 ..., 
 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]
[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ..., 
  [255 255 255 

7it [00:00, 13.52it/s]

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
Read data


In [8]:
tf.reset_default_graph()

In [10]:
n_samples = int(len(data))
training_epochs = 20
batch_size = 1
display_step = 1

autoencoder = VariationalAutoencoder(
    n_hidden=200,
    optimizer=tf.train.AdamOptimizer(learning_rate = 0.001))

ValueError: Variable w1 already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:

  File "/Users/Jimmy/Projects/DLRCev3/unsupervised_models/unsupervised_models/variational_autoencoder.py", line 41, in _initialize_weights
    initializer=tf.contrib.layers.xavier_initializer())
  File "/Users/Jimmy/Projects/DLRCev3/unsupervised_models/unsupervised_models/variational_autoencoder.py", line 9, in __init__
    network_weights = self._initialize_weights()
  File "<ipython-input-9-85c8302c5ab6>", line 8, in <module>
    optimizer=tf.train.AdamOptimizer(learning_rate = 0.001))


In [29]:
data

array([ array([[[181, 183, 182],
        [178, 180, 179],
        [175, 177, 176],
        ..., 
        [133, 135, 132],
        [126, 128, 125],
        [123, 125, 122]],

       [[175, 177, 176],
        [176, 178, 177],
        [171, 173, 172],
        ..., 
        [136, 138, 135],
        [130, 132, 129],
        [118, 120, 117]],

       [[161, 163, 162],
        [167, 169, 168],
        [160, 162, 161],
        ..., 
        [122, 124, 121],
        [114, 116, 113],
        [ 93,  95,  92]],

       ..., 
       [[ 25,  11,  26],
        [ 27,  13,  28],
        [ 29,  15,  30],
        ..., 
        [ 22,   9,  19],
        [ 23,  10,  20],
        [ 23,  10,  20]],

       [[ 26,  12,  27],
        [ 28,  14,  29],
        [ 30,  16,  31],
        ..., 
        [ 22,   9,  19],
        [ 23,  10,  20],
        [ 23,  10,  20]],

       [[ 28,  11,  27],
        [ 30,  13,  29],
        [ 31,  14,  30],
        ..., 
        [ 22,   9,  19],
        [ 23,  10,  20],
        [ 

In [32]:
%load_ext autoreload
%autoreload 1
X_train =  data
get_batch_gen = get_batch(data, batch_size)
print(data.shape)
for epoch in range(training_epochs):
    avg_cost = 0.
    total_batch = int(n_samples / batch_size)
    # Loop over all batches
    for batch_xs in get_batch(data, batch_size):
        # Fit training using batch data
        print(batch_xs.dtype)
        cost = autoencoder.partial_fit(batch_xs)
        # Compute average loss
        avg_cost += cost / n_samples * batch_size

    # Display logs per epoch step
    if epoch % display_step == 0:
        print("Epoch:", '%d,' % (epoch + 1),
              "Cost:", "{:.9f}".format(avg_cost))

print("Total cost: " + str(autoencoder.calc_total_cost(X_test)))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
(7,)
object


ValueError: setting an array element with a sequence.